

Science_computers_easy =[
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "The programming language ` Python`  is based off a modified version of ` JavaScript` .", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "Pointers were not used in the original C programming language  they were added later on in C++.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "` HTML`  stands for Hypertext Markup Language.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "In most programming languages, the operator ++ is equivalent to the statement ` += 1` .", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy", "question": "The Python programming language gets its name from the British comedy group ` Monty Python.` ", "correct_answer": "True", "incorrect_answers": ["False"]}]
Science_computers_meidum=[{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The HTML5 standard was published in 2014.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The first computer bug was formed by faulty wires.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"FLAC stands for ` Free Lossless Audio Condenser` &#039 ","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The open source program Redis is a relational database server.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"AMD created the first consumer 64-bit processor.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"Early RAM was directly seated onto the motherboard and could not be easily removed.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"A Boolean value of ` 0`  represents which of these words?","correct_answer":"False","incorrect_answers":["True"]}]
Science_nature_easy=[{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Igneous rocks are formed by excessive heat and pressure.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Salt is 100% composed of Sodium.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"An atom contains a nucleus.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"An Astronomical Unit is the distance between Earth and the Moon.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"An average human can go two weeks without water.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Psychology is the science of behavior and mind.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Water always boils at 100&deg C, 212&deg F, 373.15K, no matter where you are.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"Not including false teeth  A human has two sets of teeth in their lifetime.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"easy","question":"A plant that has a life cycle for more than a year is known as an annual.","correct_answer":"False","incorrect_answers":["True"]}]
Science_nature_medium=[{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"A person can get sunburned on a cloudy day.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"The planet Mars has two moons orbiting it.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"A defibrillator is used to start up a heartbeat once a heart has stopped beating.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Shrimp can swim backwards.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Type 1 diabetes is a result of the liver working improperly.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Anatomy considers the forms of macroscopic structures such as organs and organ systems.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Sugar contains fat.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science & Nature","type":"boolean","difficulty":"medium","question":"Sound can travel through a vacuum.","correct_answer":"False","incorrect_answers":["True"]}]
Video_games_easy=[{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In ` Mario Kart 64` , Waluigi is a playable character.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Tetris is the #1 best-selling video game of all-time.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039  history.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In ` Undertale` , the main character of the game is Sans.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Activision created Battlefield 1.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"` Sonic the Hedgehog 2`  originally was going to have a time travel system.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In the ` S.T.A.L.K.E.R.`  series, the Freedom faction wishes to destroy the supernatural area known as  ` the Zone` .","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Codemasters is the developer of the Gran Turismo series.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Each piece in Tetris is called a tetris.","correct_answer":"False","incorrect_answers":["True"]}]
Video_games_medium=[{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In World of Warcraft lore, Thrall is the original wielder of ` Doomhammer` .","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In ` Overwatch,`  an allied McCree will say ` Step right up`  upon using his ultimate ability Deadeye.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"Pistons were added to Minecraft in Beta 1.5.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In ` Starbound` , the track played by the Decorated Music Box is named ` Atlas` .","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"The character that would eventually become Dr. Eggman was considered for the role of Sega&#039 s new flagship mascot before Sonic was.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In the Season One Championship of ` League of Legends` , the highest achievable rank was Diamond.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In career mode of ` Need for Speed: Underground 2` , the first car the player can drive is the BMW M3 GTR.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"During pre-production of ` Super Mario Bros.` , Mario originally was meant to shoot bullets.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"Shang Tsung is a playable character in Mortal Kombat XL.","correct_answer":"False","incorrect_answers":["True"]}]
raspuns= input('''select the type of the game:
1: Science and computers - easy
2: Science and computers - medium
3: Science and nature - easy
4: Science and nature - medium
5: Video games - easy
6: Video games -meidum
''')
if raspuns == "1":
    question_data = Science_computers_easy
elif raspuns=="2":
    question_data=Science_computers_meidum
elif raspuns=="3":
    question_data=Science_nature_easy
elif raspuns=="4":
    question_data=Science_nature_medium
elif raspuns=="5":
    question_data=Video_games_easy
elif raspuns=="6":
    question_data=Video_games_medium
